version: '3'

services:
  qbit:
    image: qbittorrentofficial/qbittorrent-nox:4.4.5-1
    container_name: qbittorrent-nox
    ports:
      - 127.0.0.1:6881:6881
      - 127.0.0.1:8080:8080
    environment:
      - QBT_EULA="accept"
      - QBT_WEBUI_PORT=8080
    restart: always
    volumes:
      - ./config:/config
      - ./downloads:/downloads

  ftp:
    image: delfer/alpine-ftp-server
    container_name: torrent-fto-server
    ports:
      - 127.0.0.1:21:21
      - 127.0.0.1:21000-21010:21000-21010
    environment:
      - USERS=${FTP_USERS}
      - MIN_PORT=21000
      - MAX_PORT=21010
    volumes:
      - ./downloads:/ftp
